[pyprland]
plugins = [
  "scratchpads",
  "magnify",
  "expose",
]

[scratchpads.term]
animation = "fromTop"
command = "ghostty --class=scratchpad"
class = "scratchpad"
size = "75% 60%"
max_size = "1920px 100%"
margin = 50
unfocus = "hide"
lazy = true
